call npx truffle test ./test/1.NestMining.Post.test.js
call npx truffle test ./test/2.NestMining.Post.HBTC.test.js
call npx truffle test ./test/3.NestMining.Post2.test.js
call npx truffle test ./test/4.NestMining.Post.Fee.test.js
call npx truffle test ./test/5.NestMining.Post.Fee.HBTC.test.js
call npx truffle test ./test/6.NestMining.Post.Reward.test.js
call npx truffle test ./test/7.NestMining.Post.Reward.HBTC.test.js
call npx truffle test ./test/8.NestPriceFacade.triggeredPrice.test.js
call npx truffle test ./test/9.NestMining.BiteToken.test.js
call npx truffle test ./test/10.NestMining.BiteEth.test.js
call npx truffle test ./test/11.NTokenController.test.js
call npx truffle test ./test/12.NestVote.test.js
call npx truffle test ./test/13.NestRedeeming.test.js
call npx truffle test ./test/14.NNIncome.test.js
call npx truffle test ./test/15.NestMining.CloseList2.test.js
call npx truffle test ./test/16.NestMining.Post.shares.test.js
call npx truffle test ./test/17.NestMining.BiteToken.level4.test.js
call npx truffle test ./test/18.NestRedeeming.Redeem.test.js
call npx truffle test ./test/19.NTokenController.Open.test.js
call npx truffle test ./test/20.NestLedger.test.js
call npx truffle test ./test/21.NestMapping.test.js
call npx truffle test ./test/22.NestPriceFacade.test.js
call npx truffle test ./test/23.NestMining.test.js
call npx truffle test ./test/24.NestPriceFacade.test2.js
call npx truffle test ./test/25.NToken.test.js
call npx truffle test ./test/26.NestMining.test2.js
call npx truffle test ./test/27.NestMining.Collect.test.js
call npx truffle test ./test/28.NestBase.test.js
call npx truffle test ./test/29.NestPriceFacade.test3.js
call npx truffle test ./test/30.NestMining.Proxy.test.js
